<?php

namespace App\Models;

use App\Traits\TranslatableTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Modules\FileManager\App\Models\File;

class Employee extends Model
{
    use TranslatableTrait;

    protected $fillable = [
        'file_id',
        'status',
        'sort',
        'is_home',
        'is_about',
        'updated_at',
    ];

    protected $with = ['translation'];

    protected $hidden = ['translation'];

    protected static mixed $translationModel = EmployeeTranslation::class;

    public static array $translatable = [
        'full_name',
        'position',
        'content',
    ];

    public function socials(): MorphToMany
    {
        return $this->morphToMany(SocialNetwork::class, 'socialable', 'socialables', 'socialable_id', 'social_id')->withPivot('link');
    }

    public function file(): BelongsTo
    {
        return $this->belongsTo(File::class, 'file_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saved(function ($model) {
            if ($model->is_home) {
                self::withoutEvents(function () use ($model) {
                    self::where('is_home', 1)
                        ->where('id', '!=', $model->id)
                        ->update(['is_home' => 0]);
                });
            }
            if ($model->is_home) {
                self::withoutEvents(function () use ($model) {
                    self::where('is_about', 1)
                        ->where('id', '!=', $model->id)
                        ->update(['is_about' => 0]);
                });
            }
        });
    }
}
