<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Lang;

class Feedback extends Model
{
    protected $fillable = [
        "full_name",
        "category_id",
        "region_id",
        "email",
        "phone",
        "message",
        "status",
        "message_id",
        "ip",
    ];

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    public function region(): BelongsTo
    {
        return $this->belongsTo(Region::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function (Feedback $feedback) {
            $feedback->ip = request()->ip();
        });
        Lang::setLocale("uz");
        static::created(function (Feedback $feedback) {
            $text = <<<TEXT
🙎‍♂️ <b>F.I.SH:</b>  {$feedback->full_name}
📧 <b>EMAIL:</b>  {$feedback->email}
📞 <b>TELEFON:</b>  {$feedback->phone}
©️ <b>KATEGORI:</b>  {$feedback->category->translation->title}
🏙 <b>REGION:</b>  {$feedback->region->translation->name}
📝 <b>XABAR:</b>  {$feedback->message}
TEXT;

            $response = Http::post("https://api.telegram.org/bot6618232267:AAGwG8FwAbK1mwETYYGKVLt9VPvCuIospYw/sendMessage", [
                "chat_id" => -1002075164774,
                "text" => $text,
                "parse_mode" => "HTML",
                "disable_web_page_preview" => false,
                "reply_markup" => [
                    "inline_keyboard" => [
                        [
                            ["text" => "Ko'rish", "url" => "https://admin.acapitatrading.uz/feedbacks/{$feedback->id}"]
                        ]
                    ]
                ]
            ])->json();

            $feedback->message_id = $response["result"]["message_id"];
            $feedback->save();
        });
    }

}
